Home work5
LezgiHaly/Magic-ball pull request #1
Opened 2024-05-29 14:52 UTC by LezgiHaly

2024-05-29 14:58 UTC, LezgiHaly commented
https://github.com/LezgiHaly/Magic-ball/assets/101892549/2aac3cb0-3274-4884-b8e5-bb9c69a86351

2024-05-29 19:11 UTC, danyaao requested changes
Так, а где появление и исчезновение текста через AnimatedOpacity? И не совсем понял, а зачем зум? Если хочешь через зум имитировать загрузку, то можно, но шар нужно возвращать в предыдущее положение и давать возможность сделать запрос заново

При отключенном интернете состояния ошибки не будет, т.к. нет try/catch

В целом неплохо, но эти моменты бы надо поправить

2024-05-29 19:11 UTC, danyaao commented on Magic-ball/lib/assets/styles.dart
> +
Переносы между комментариями и кодом обычно не нужны

2024-05-29 19:11 UTC, danyaao commented on Magic-ball/lib/bloc/ball_bloc.dart
> +        emit(BallEror(title: title));
error

2024-05-29 19:11 UTC, danyaao commented on Magic-ball/lib/repositories/ipi.dart
> +class ApiRepositories {
Название немного странное, зачем во множественном числе?

2024-05-29 19:11 UTC, danyaao commented on Magic-ball/lib/repositories/ipi.dart
> +    return data['reading'] ?? AppString.eror;
Нужно обернуть в try/catch

2024-05-30 20:58 UTC, danyaao requested changes
А какая проблема возникла с тряской? Вроде у тебя правильный вариант, разве что попробуй super.init перенести в начало init, если проблема останется, скинь мне, что конкретно происходит

2024-05-30 20:58 UTC, danyaao commented on Magic-ball/lib/ui/screen/ball_acrren.dart
> +          child: BlocBuilder<BallBloc, BallState>(
Смотри, у тебя виджет уже появляется с текстом, плавного появления нет. Скорее всего, проблема в том, что он у тебя уже создается с _opacityBg = 1, попробуй поправить

2024-06-03 16:00 UTC, danyaao approved these changes

2024-06-03 16:00 UTC, danyaao commented on Magic-ball/lib/repositories/ipi.dart
> +      // ignore: unused_catch_clause
Кажется, уже не нужен игнор

2024-06-03 16:00 UTC, danyaao commented on Magic-ball/lib/ui/screen/ball_acrren.dart
> +      _opacityBg = _opacityBg == 0 ? 1 : 0;
Раз это два противоположных опасити, то можно в коде использовать просто 1 - _opacity

2024-06-03 16:00 UTC, danyaao commented on Magic-ball/lib/ui/screen/ball_acrren.dart
> +        Timer(_duration, _ballState);
Немного странное решение, но раз работает, то хорошо

2024-06-03 16:00 UTC, danyaao commented on Magic-ball/lib/ui/screen/ball_acrren.dart
> +  void _ballState() {
Немного неудачное название метода, вообще не очевидно, что он делает

2024-06-03 16:36 UTC, LezgiHaly commented on Magic-ball/lib/ui/screen/ball_acrren.dart
> +        Timer(_duration, _ballState);
> Немного странное решение, но раз работает, то хорошо

костыли наше все)))

2024-07-16 14:34 UTC, merged